### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**
1.x match latest stable go version

### CODE REVIEW

**Comment by dvrkps** [comment]
@sg3des @bradleyjkemp ping :) happy holidays.

**Comment by bradleyjkemp** [comment]
Ack. I added a t.Helper() call to cupaloy which was only introduced in 1.9 so this will definitely not build on 1.8

**Comment by dvrkps** [comment]
@bradleyjkemp merge ?

**Comment by bradleyjkemp** [comment]
Would do but sorry I don't have any merge rights 😃

**Pull request merged**
